version: 2s

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "@types/node"
        versions:
          - "version-update:sermver-major"
