name: Publish Release

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 10.x

      - name: install dependencies
        run: yarn install

      - name: build site
        run: yarn build

      - name: copy output
        uses: canastro/copy-action@0.0.2
        with:
          source: "build/."
          target: "docs/"
          flags: "-r"
      - name: publish site
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: publish site changes."